/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwardCard: typeof import('./src/components/AwardCard.vue')['default']
    CampaignHeader: typeof import('./src/components/CampaignHeader.vue')['default']
    CountdownTimer: typeof import('./src/components/CountdownTimer.vue')['default']
    ImageLightbox: typeof import('./src/components/ImageLightbox.vue')['default']
    NominateModal: typeof import('./src/components/NominateModal.vue')['default']
    NomineeCard: typeof import('./src/components/NomineeCard.vue')['default']
    NomineeDetailsModal: typeof import('./src/components/NomineeDetailsModal.vue')['default']
    OtpModal: typeof import('./src/components/OtpModal.vue')['default']
    PhoneInput: typeof import('./src/components/PhoneInput.vue')['default']
    ResultsBar: typeof import('./src/components/ResultsBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/Toast.vue')['default']
    VoteModal: typeof import('./src/components/VoteModal.vue')['default']
    WinnerBadge: typeof import('./src/components/WinnerBadge.vue')['default']
  }
}
